import requests 
import json
import re

from config import ACCESS_KEY, SECRET_KEY


def get_variables(document_url):
    """
    Generates our JSON format based on a url. Starts by getting the onshape document variables, turning them into json, 
    and then formatting it correctly for our database.
    :param document_url: the url of the onshape document
    :return: the final json as a string
    """

    # Use the API keys generated from the Onshape developer portal 
    api_keys = (ACCESS_KEY, SECRET_KEY)

    variable_url = build_variables_url(document_url)

    onshape_json = fetch_onshape_document_variables_json(api_keys, variable_url)
    return onshape_json_to_our_json(onshape_json) 

def build_variables_url(document_url):
    """
    Builds a special variable url in order to fetch the variable data from the document through the Onshape API
    :param document_url: the url of the onshape document
    """
    m = re.match(r"^https?://cad.onshape.com/documents/([0-9a-f]+)/([wv])/([0-9a-f]+)/e/([0-9a-f]+)", document_url)
    return f'https://cad.onshape.com/api/v5/variables/d/{m.group(1)}/{m.group(2)}/{m.group(3)}/e/{m.group(4)}/variables'


def fetch_onshape_document_variables_json(api_keys, api_url):
    """
    Takes an api_url and the api keys and fetches the variable document data
    :param api_url: the url that variables will be taken from
    :param api_keys: the api keys
    :return: the onshape document variables as a JSON
    """
    # Optional query parameters can be assigned 
    params = {'includeValuesAndReferencedVariables':True}

    # Define the header for the request 
    headers = {'Accept': 'application/json;charset=UTF-8;qs=0.09',
            'Content-Type': 'application/json'}

    # Putting everything together to make the API request 
    response = requests.get(api_url, 
                            params=params, 
                            auth=api_keys, 
                            headers=headers)

    return response.json()[0]['variables']


def onshape_json_to_our_json(onshape_json):
    """
    Takes the JSON from the scad file and formats it to our template
    :param onshape_json: the JSON generated by the call to onshape
    :return: Our JSON as a dict
    """

    our_json = []
    for i, current_onshape_var in enumerate(onshape_json):
        # the elements attached to every variable
        name = current_onshape_var['name']
        desc = current_onshape_var['description']
        # default = current_onshape_var['initial']
        # group = current_onshape_var['group']
        type = current_onshape_var['type']

        if type == 'LENGTH':
            value, label = current_onshape_var['value'].split(' ')
            value = float(value)*1000 # convert to mm from meters
            label = 'mm'
        elif type == 'ANGLE':
            value, label = current_onshape_var['value'].split(' ')
        elif type == 'NUMBER':
            value = current_onshape_var['value']
            label = ''
        elif type == 'ANY':
            value = current_onshape_var['value']
            label = ''


        our_json.append(
            {
                'name': name,
                'desc': desc,
                'default': value,
                # 'group': group,
                'label': label
            }
        )

        # TODO: add functionality for groups and extra options within onshape description box
        # need to find out how to create groups, this method seems to completely avoid folders

        # # Extra Options
        # for extra in current_onshape_var:
        #     # The drop-down menu
        #     if extra == 'options':
        #         our_json[i]['style'] = 'dropdown'
        #         # todo: ask if this format is okay
        #         our_json[i]['options'] = current_onshape_var['options']

    # todo: change this and tests to output a string
    return our_json